# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  lua54_config = debug
  moon_config = debug
  pb_config = debug
  crypt_config = debug
  aoi_config = debug
  sharetable_config = debug
  clonefunc_config = debug
endif
ifeq ($(config),release)
  lua54_config = release
  moon_config = release
  pb_config = release
  crypt_config = release
  aoi_config = release
  sharetable_config = release
  clonefunc_config = release
endif

PROJECTS := lua54 moon pb crypt aoi sharetable clonefunc

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lua54:
ifneq (,$(lua54_config))
	@echo "==== Building lua54 ($(lua54_config)) ===="
	@${MAKE} --no-print-directory -C build/projects/lua54 -f Makefile config=$(lua54_config)
endif

moon: lua54 aoi crypt pb sharetable clonefunc
ifneq (,$(moon_config))
	@echo "==== Building moon ($(moon_config)) ===="
	@${MAKE} --no-print-directory -C build/projects/moon -f Makefile config=$(moon_config)
endif

pb:
ifneq (,$(pb_config))
	@echo "==== Building pb ($(pb_config)) ===="
	@${MAKE} --no-print-directory -C build/projects/pb -f Makefile config=$(pb_config)
endif

crypt:
ifneq (,$(crypt_config))
	@echo "==== Building crypt ($(crypt_config)) ===="
	@${MAKE} --no-print-directory -C build/projects/crypt -f Makefile config=$(crypt_config)
endif

aoi:
ifneq (,$(aoi_config))
	@echo "==== Building aoi ($(aoi_config)) ===="
	@${MAKE} --no-print-directory -C build/projects/aoi -f Makefile config=$(aoi_config)
endif

sharetable:
ifneq (,$(sharetable_config))
	@echo "==== Building sharetable ($(sharetable_config)) ===="
	@${MAKE} --no-print-directory -C build/projects/sharetable -f Makefile config=$(sharetable_config)
endif

clonefunc:
ifneq (,$(clonefunc_config))
	@echo "==== Building clonefunc ($(clonefunc_config)) ===="
	@${MAKE} --no-print-directory -C build/projects/clonefunc -f Makefile config=$(clonefunc_config)
endif

clean:
	@${MAKE} --no-print-directory -C build/projects/lua54 -f Makefile clean
	@${MAKE} --no-print-directory -C build/projects/moon -f Makefile clean
	@${MAKE} --no-print-directory -C build/projects/pb -f Makefile clean
	@${MAKE} --no-print-directory -C build/projects/crypt -f Makefile clean
	@${MAKE} --no-print-directory -C build/projects/aoi -f Makefile clean
	@${MAKE} --no-print-directory -C build/projects/sharetable -f Makefile clean
	@${MAKE} --no-print-directory -C build/projects/clonefunc -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lua54"
	@echo "   moon"
	@echo "   pb"
	@echo "   crypt"
	@echo "   aoi"
	@echo "   sharetable"
	@echo "   clonefunc"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"