# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug_linux
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_linux)
  lua53_config = debug_linux
  rapidjson_config = debug_linux
  protobuf_config = debug_linux
  core_config = debug_linux
  moon_config = debug_linux
endif
ifeq ($(config),release_linux)
  lua53_config = release_linux
  rapidjson_config = release_linux
  protobuf_config = release_linux
  core_config = release_linux
  moon_config = release_linux
endif

PROJECTS := lua53 rapidjson protobuf core moon

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lua53:
ifneq (,$(lua53_config))
	@echo "==== Building lua53 ($(lua53_config)) ===="
	@${MAKE} --no-print-directory -C build/lua53 -f Makefile config=$(lua53_config)
endif

rapidjson:
ifneq (,$(rapidjson_config))
	@echo "==== Building rapidjson ($(rapidjson_config)) ===="
	@${MAKE} --no-print-directory -C build/rapidjson -f Makefile config=$(rapidjson_config)
endif

protobuf:
ifneq (,$(protobuf_config))
	@echo "==== Building protobuf ($(protobuf_config)) ===="
	@${MAKE} --no-print-directory -C build/protobuf -f Makefile config=$(protobuf_config)
endif

core:
ifneq (,$(core_config))
	@echo "==== Building core ($(core_config)) ===="
	@${MAKE} --no-print-directory -C build/core -f Makefile config=$(core_config)
endif

moon: lua53 core rapidjson protobuf
ifneq (,$(moon_config))
	@echo "==== Building moon ($(moon_config)) ===="
	@${MAKE} --no-print-directory -C build/moon -f Makefile config=$(moon_config)
endif

clean:
	@${MAKE} --no-print-directory -C build/lua53 -f Makefile clean
	@${MAKE} --no-print-directory -C build/rapidjson -f Makefile clean
	@${MAKE} --no-print-directory -C build/protobuf -f Makefile clean
	@${MAKE} --no-print-directory -C build/core -f Makefile clean
	@${MAKE} --no-print-directory -C build/moon -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_linux"
	@echo "  release_linux"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lua53"
	@echo "   rapidjson"
	@echo "   protobuf"
	@echo "   core"
	@echo "   moon"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"