return {
    AbstractEntityIndex = require("entitas.AbstractEntityIndex"),
    Collector = require("entitas.Collector"),
    Context = require("entitas.Context"),
    Delegate = require("entitas.Delegate"),
    Entity = require("entitas.Entity"),
    EntityIndex = require("entitas.EntityIndex"),
    Group = require("entitas.Group"),
    GroupEvent = require("entitas.GroupEvent"),
    MakeComponent = require("entitas.MakeComponent"),
    Matcher = require("entitas.Matcher"),
    PrimaryEntityIndex = require("entitas.PrimaryEntityIndex"),
    Systems = require("entitas.Systems"),
    ReactiveSystem = require("entitas.ReactiveSystem"),
}